[[/* format all `app_` variables in the best-possible way */]]
[[- define "configuration" ]]
  [[- range $name, $value := .my -]]
  [[ if and ($name | hasPrefix "app_") ($value) ]]
  [[- if (eq "slice" (kindOf $value)) ]]
  [[ $name | trimPrefix "app_" | upper ]] = "[[ $value | toStrings | join " " ]]"
  [[- else if (or (eq "int" (kindOf $value)) (eq "bool" (kindOf $value))) ]]
  [[ $name | trimPrefix "app_" | upper ]] = [[ $value ]]
  [[- else ]]
  [[ $name | trimPrefix "app_" | upper ]] = [[ $value | toString | quote ]]
  [[- end ]]
  [[- end ]]
  [[- end ]]
  DD_TAGS = "[[ .my.dd_tags | toStrings | join " " ]]"
  [[- if (eq .my.app_include_nomad_tags true) ]]
  DD_EXTRA_TAGS = "[[ .my.nomad_tags | toStrings | join " " ]]"
  [[- end ]]
  DD_APM_RECEIVER_PORT = [[ .my.ports.apm_receiver.port ]]
  [[- if .my.ports.ipc ]]
  DD_CMD_PORT = [[ .my.ports.ipc.port ]]
  [[- end ]]
  [[- if .my.ports.dogstatsd ]]
  DD_EXPVAR_PORT = [[ .my.ports.expvar.port ]]
  [[- end ]]
  [[- if .my.ports.dogstatsd ]]
  DD_USE_DOGSTATSD = true
  DD_DOGSTATSD_PORT = [[ .my.ports.dogstatsd.port ]]
  [[- end ]]
  DD_DOGSTATSD_STATS_PORT = [[ .my.ports.expvar.port ]]
  [[- if .my.ports.gui ]]
  DD_GUI_PORT = [[ .my.ports.gui.port ]]
  [[- end ]]
  [[- if .my.ports.healthcheck ]]
  DD_HEALTH_PORT = [[ .my.ports.healthcheck.port ]]
  [[- end ]]
  [[- if .my.ports.debug ]]
  DD_PROCESS_CONFIG_EXPVAR_PORT = [[ .my.ports.debug.port ]]
  [[- end ]]
[[- end ]]
