---

content: |-
  ### Inputs

  This Nomad Pack exposes configuration options via application- and Nomad-specific variables.

  #### Application

  This section describes application-specific configuration.

  {{ $prefix_app := "app_" -}}
  | Name | Description | Default |
  | ---- | ----------- | ------- |
  {{- range .Module.Inputs -}}
  {{if eq (printf "%.[1]*s" (len $prefix_app) .Name) $prefix_app }}
   | `{{ .Name }}` | {{ .Description }} | `{{ .Default }}` |
  {{- end }}
  {{- end }}

  #### Nomad

  This section describes Nomad and Nomad Pack-specific configuration.

  {{ $prefix_app := "nomad_" -}}
  | Name | Description | Default |
  | ---- | ----------- | ------- |
  {{- range .Module.Inputs -}}
  {{if eq (printf "%.[1]*s" (len $prefix_app) .Name) $prefix_app }}
   | `{{ .Name }}` | {{ .Description }} | `{{ .Default }}` |
  {{- end }}
  {{- end }}

# see https://terraform-docs.io/user-guide/configuration/formatter/
formatter: "markdown table"

# see https://terraform-docs.io/user-guide/configuration/output/
output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_PACK_DOCS -->
    {{ .Content }}
    <!-- END_PACK_DOCS -->

# see https://terraform-docs.io/user-guide/configuration/settings/
settings:
  anchor: false
  color: true
  default: true
  description: false
  escape: false
  hide-empty: true
  html: false
  indent: 3
  read-comments: false
  required: false
  sensitive: false
  type: false

# see https://terraform-docs.io/user-guide/configuration/sort/
sort:
  enabled: true
  by: name

# see https://terraform-docs.io/user-guide/configuration/sections/
sections:
  show:
    - inputs

# see https://terraform-docs.io/user-guide/configuration/version/
version: ">= 0.16.0, < 1.0.0"
